"use client";

import { useEffect, useRef, useState } from "react";
import sdk from "@stackblitz/sdk";
import { Loader2, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Props {
    files: { path: string; content: string }[];
    title?: string;
    template?: "node" | "create-react-app" | "javascript" | "typescript" | "html";
}

export default function StackBlitzEmbed({ files, title = "QueryMate Project", template = "node" }: Props) {
    const embedRef = useRef<HTMLDivElement>(null);
    const [isLoaded, setIsLoaded] = useState(false);

    const getProject = () => {
        const projectFiles: Record<string, string> = {};
        files.forEach(f => {
            projectFiles[f.path] = f.content;
        });

        // Ensure package.json exists for node template
        if (template === "node" && !projectFiles["package.json"]) {
            const mainFile = files[0]?.path || "index.js";
            projectFiles["package.json"] = JSON.stringify({
                name: "querymate-project",
                dependencies: {
                    "express": "latest"
                },
                scripts: { start: `node ${mainFile}` }
            }, null, 2);
        }

        return {
            title,
            description: "Generated by QueryMate",
            template,
            files: projectFiles,
        };
    };

    useEffect(() => {
        if (!embedRef.current) return;

        try {
            sdk.embedProject(embedRef.current, getProject(), {
                height: "100%",
                width: "100%",
                hideExplorer: false,
                hideNavigation: false,
                forceEmbedLayout: true,
                openFile: files[0]?.path || "index.js",
            }).then(() => {
                setIsLoaded(true);
            }).catch(err => {
                console.error("Error embedding StackBlitz", err);
            });
        } catch (e) {
            console.error("Failed to embed StackBlitz", e);
        }
    }, [files, title, template]);

    const handleOpenInNewTab = () => {
        sdk.openProject(getProject(), { openFile: files[0]?.path });
    };

    return (
        <div className="flex flex-col w-full h-full relative bg-gray-100 dark:bg-gray-900 overflow-hidden">
            <div className="flex items-center justify-between px-3 py-2 border-b border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900">
                <span className="text-sm font-semibold text-gray-700 dark:text-gray-300 flex items-center gap-2">
                    <svg viewBox="0 0 28 28" fill="none" className="w-5 h-5">
                        <path d="M12.747 16.273h-7.46L18.913 1.5l-3.65 7.127h7.46L8.85 26.5l3.897-10.227z" fill="currentColor" />
                    </svg>
                    StackBlitz IDE
                </span>
                <Button variant="outline" size="sm" onClick={handleOpenInNewTab} className="h-7 text-xs flex items-center gap-1">
                    <ExternalLink className="w-3.5 h-3.5" /> Open
                </Button>
            </div>
            <div className="flex-1 w-full relative">
                {!isLoaded && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-gray-50/50 dark:bg-gray-900/50 z-10 gap-2">
                        <Loader2 className="w-6 h-6 animate-spin text-blue-500" />
                        <span className="text-xs text-gray-500 font-medium">Booting StackBlitz Environment...</span>
                    </div>
                )}
                <div ref={embedRef} className="w-full h-full" />
            </div>
        </div>
    );
}
